# Generated by Django 2.1.4 on 2019-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('account_number', models.BigIntegerField()),
                ('card_number', models.BigIntegerField()),
                ('csv', models.IntegerField()),
                ('date_of_account_creation', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
