# Generated by Django 2.1.4 on 2019-02-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='epinto6', max_length=20),
            preserve_default=False,
        ),
    ]
